### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by Peppazzz91** [hoantv/CarSimulatorFirmware#12]
is possible to have source code for porting on stm32 blue pill (STM32F103C8T6 based)?
It was capable to run a ffb firmware (i know a **closed** source firmware thath works, https://www.facebook.com/EMCDeveloper/), but pin used in MMOS does not exist on this board

**Comment by hoantv** [comment]
this firmware can not be used in STM32F103C8T6 :).

**Comment by Peppazzz91** [comment]
for what reason?

**Comment by hoantv** [comment]
They have different hardware architecture :)!

**Comment by Peppazzz91** [comment]
sorry, i made a mistake.
I read this
![ffbgithub](https://user-images.githubusercontent.com/65404453/87099942-5acde480-c24b-11ea-8479-921ca70b79ae.png)
so i think that is an open firmware with source code and that works on stm32 cortex "m" based architecture...........................
