### ISSUE TITLE
Save steering wheel settings to flash

### ISSUE THREAD

**Issue by Unoqueva** [hoantv/CarSimulatorFirmware#15]
Every time you start the board, it loads the default configuration values, instead of the last ones adjusted with the GUI, it would be nice that once the parameters were set in the GUI they will be saved in the flash of the board, so there is no need to open the GUI every time you want to use the steering wheel.

**Comment by hoantv** [comment]
Yes, i will be added in near future. It was added before. But i removed due to calibration. Now dont need calibration so can add it again :)!

**Comment by hoantv** [comment]
Done!
