### ISSUE TITLE
Support for Absolute Encoders?

### ISSUE THREAD

**Issue by Tzigane** [hoantv/CarSimulatorFirmware#21]
Do you have any plans to support absolute encoders?  I have a BISS C 22bit which I would love to use with this.

Many Thanks

**Comment by Tzigane** [comment]
Closing as I've just read in Discord you are planning to do this.

**Comment by hoantv** [comment]
Problem is with absolute, only read directly from encoder, read via servo driver is too slow. Almost industrial servo driver only has less than 112000bps. So it is only used for beltbase :(!
