### ISSUE TITLE
Wrong direction FFB for CCW direction on LFS

### ISSUE THREAD

**Issue by tronicgr** [hoantv/CarSimulatorFirmware#29]
While the force is correct direction when no in game and the wheel centers perfectly both directions, in LFS it reverses direction for the CCW direction. See this video: [https://youtu.be/UvV70YOY9iM](https://youtu.be/UvV70YOY9iM) . The MMOS firmware works perfectly on LFS and same hardware (TDD board). The settings of the board can be seen on the video as well.

Thanks
Thanos

**Comment by hoantv** [comment]
Fixed with V1
