### ISSUE TITLE
e-Stop Leds

### ISSUE THREAD

**Issue by Mageign** [hoantv/CarSimulatorFirmware#30]
Maybe add support for external led (not the ones on the board).
One for e-Stop engaged, another for e-Stop disengaged ?

**Comment by hoantv** [comment]
You mean stm32 discovery? Next version > 2.3 i added 2 led for some information. But with estop, have to becareful with it :)!

**Comment by Mageign** [comment]
Yes Stm32 discovery.
What is the problem with e-Stop ?
I just think a led to indicate e-Stop is engaged, and another for disengaged would be great.

**Comment by hoantv** [comment]
With e-stop, you must connect with external power. So it doesnt relate to stm32. Connect led directly with estop. 
this feature does not need on stm32.

**Comment by Mageign** [comment]
How can you connect 2 leds with 2 wires ?

**Comment by hoantv** [comment]
> How can you connect 2 leds with 2 wires ?

Connect a led continuously with estop button

**Comment by Mageign** [comment]
So it is not possible to connect 2 leds ...

**Comment by groybe** [comment]
> So it is not possible to connect 2 leds ...

It is possible. Depend what you have wire estop to. Connect one led to normally closed and one to normally open terminal on estop.

**Comment by hoantv** [comment]
This doesnt relate to firmware. So i close it.

**Comment by Mageign** [comment]
I hoped you could add it in the firmware.
Thanks for your work ...
