### ISSUE TITLE
No force feedback with DAC

### ISSUE THREAD

**Issue by Mageign** [hoantv/CarSimulatorFirmware#31]
Using the TDD Board, I tried the option for internal or external DAC and ended up with a dead wheel with no forces applied in UI or in game.

**Comment by hoantv** [comment]
you have to enable internal DAC to use. go to discord for more information.

**Comment by Mageign** [comment]
Even if I select "External DAC" ?

**Comment by Mageign** [comment]
Seems like you changed the pinout so the DAC is unusable.

**Comment by hoantv** [comment]
No, dac pin is fixed. Cannot change it. Problem with your wiring.
