### ISSUE TITLE
Game-Specific Config dirt 2, Automobilista 2

### ISSUE THREAD

**Issue by Nemosi13** [hoantv/CarSimulatorFirmware#32]
Hi hoan I have been following you for some time and I admire your work.

I tried the game configurations for dirty 2 and everything works quite well, but the vibrations due to the contact of the wheels with the different surfaces of the tracks are almost nil, I made a slight modification to the line suggested by you to add a little more ffb and something has improved, however I have read that the dirty ffb is not optimized very well.

<device id="{60006699-0000-0000-0000-504944564944}" name="vnm_wheelbase" priority="100" type="wheel" ffb_force="20" official="false"/>

To have a bigger playground, you could add the Automobilista 2 configuration specs.

Thanks and good job

**Comment by hoantv** [comment]
Go to my discord. There is channel to guide how to setup for Dirt2 and AM2
