### ISSUE TITLE
Wheel Bug since ui v2.3

### ISSUE THREAD

**Issue by Mageign** [hoantv/CarSimulatorFirmware#33]
Wheel rotates constantly from end to end since v2.3... on TDD Board+AASD-30A+Big Mige.

**Comment by chicknsoup** [comment]
Thanks for filing issue. Please update to the latest UI version.

Next time, it would be more helpful if you fill out the following form (which is clearly stated in Readme file)

1. Brief description of the issue
2. Which firmware and UI version are you using?
3. Windows version?
4. Which feature is broken?
5. Does it occur frequently? (Rarely, sometimes, always, etc.)
6. Steps to re-produce the issue?
7. Screenshots and logs
8. Other information
