### ISSUE TITLE
debug window in ui 2.6.1.2

### ISSUE THREAD

**Issue by phongshader** [hoantv/CarSimulatorFirmware#37]
Debug window corrupted
fw 0.23.2.7
ui 2.6.1.2
Win10

![vnmerror](https://user-images.githubusercontent.com/38082624/131229588-b786a0cf-cc02-4270-8f28-2141f6359e1e.png)
![debugtabvnm2612](https://user-images.githubusercontent.com/38082624/131229505-f4bb26ad-e7e7-47e4-9b78-085705c590b9.png)

**Comment by chicknsoup** [comment]
Thanks for reporting. The issue has been addressed with v2.6.1.3. Please update your UI.
