### ISSUE TITLE
Which Analog in for Shifter?

### ISSUE THREAD

**Issue by C1500** [hoantv/CarSimulatorFirmware#40]
Hi Hoan
Today i tested new V1 Firmware and the wheel and pedals work great. (PC0 to PC3)
So i want to test shifter.
Which inputs do you use for the analog inputs for the shifter?
There is no information in the wiki
Kind regards
C1500

**Comment by hoantv** [comment]
shifter is being added :)!

**Comment by hoantv** [comment]
> Nice to hear ;o) I ordered the STM32H743VIT6 for a update to V2 Which pins have you selected? PC4 and PC5 as discussed last year?
> 
> BTW: where can i find V2?

go to discord to discuss :)
